#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    #colorscheme = "desert"
#colorscheme = "codedark"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

    #guifont = "SourceCodePro Nerd Font Mono:h11"
    bootstrap_before = "myspacevim#before"
    
    default_indent = 4
    expand_tab = true


# 添加自定义主题：https://github.com/mhartington/oceanic-next
[[custom_plugins]]
  repo = "tomasiser/vim-code-dark"
  merged = 0

[[custom_plugins]]
    repo = 'https://gitee.com/mirrors_octol/vim-cpp-enhanced-highlight'
    merged = 0

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = "lang#c"
  enable_clang_syntax_highlight = true

[[layers]]
  name = "lsp"
  filetypes = [
    "c",
    "cpp"
  ]
  [layers.override_cmd]
    c = ["clangd"]

[[layers]]
  name = "lang#python"
