# https://clangd.llvm.org/config#files
# 感觉配置了也不生效， 但是 clangd 官方文档写的内容太少了。。
CompileFlags:
    # Treat code as C++, use C++11 standard, enable more warnings
    Add: [-xc++, -std=c++17, -Wall, -Wno-missing-prototypes]
    Add: [-Wall, -Wno-missing-prototypes]
    # Remove extra warnings specified in compile commands.
    # Single value is also acceptable, same as "Remove: [-mabi]"
    Remove: -mabi
Diagnostics:
    # Tweak Clang-Tidy checks.
    ClangTidy:
        #Add: [performance*, modernize*, readability*]
        Remove: [modernize-use-trailing-return-type]
        CheckOptions:
            #readability-identifier-naming.VariableCase: CamelCase
            readability-identifier-naming.VariableCase: lower_case
---
If:
  PathMatch: .*\.hpp
CompileFlags:
  Add: [-Wno-unused-function, -std=c++11]
---
If:
  PathMatch: .*\.cpp
CompileFlags:
  Add: [-Wno-unused-function, -std=c++11]
---
# -Wunused-member-function false positive:
# https://github.com/clangd/clangd/issues/363
# CompileFlagsButNotReally: # broken here
#   Add: [-Wno-unused-macros,-Wno-unused-member-function,-Wno-unused-template]
# Diagnostics:
#   ClangTidy:
#     Add: *
